name: Rust

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  checks:
    name: Check on ${{ matrix.oses.os }}
    runs-on: ${{ matrix.oses.os }}
    strategy:
      fail-fast: false
      matrix:
        triple:
          - { os: 'ubuntu-latest',  target: 'x86_64-unknown-linux-gnu', cross: false }
          - { os: 'windows-latest', target: 'x86_64-pc-windows-msvc',   cross: false }

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Checking formatting
      run: |
        rustup component add rustfmt
        cargo fmt --check
    - name: Checking linting
      run: | 
        rustup component add clippy
        cargo clippy --all --all-targets --all-features -- -D warnings
